@Astate_HostAddress = http://localhost:5100


###
### Récupérer toutes les notes d'un utilisateur spécifique
###

GET @Astate_HostAddress/api/Note/user/1

###
### Récupérer toutes les notes d'un utilisateur spécifique
###

GET @Astate_HostAddress/api/Note/user/1

###
### Créer une nouvelle note
###

POST @Astate_HostAddress/api/Note/
Content-Type: application/json

{
    "IdOwner": 1,
    "Title": "Nouvelle Note",
    "Description": "Description de la nouvelle note",
    "Content": "Contenu de la nouvelle note",
    "Img": "image.jpg"
}

###
### Mettre à jour une note
###

PUT @Astate_HostAddress/api/Note/5
Content-Type: application/json

{
    "Id": 5,
    "IdOwner": 1,
    "Title": "Note mise à jour",
    "Description": "Description mise à jour",
    "Content": "Contenu mis à jour",
    "Img": "image.jpg"
}

###
### Supprimer une note
###

DELETE @Astate_HostAddress/api/Note/5


###
### Récupérer un utilisateur par son identifiant
###

GET @Astate_HostAddress/api/Utilisateur/1

###
### Créer un nouvel utilisateur
###

POST @Astate_HostAddress/api/Utilisateur
Content-Type: application/json

{
    "Email": "Nom.Prénom@example.com",
    "Password": "password123",
}

###
### Mettre à jour un utilisateur existant
###

PUT @Astate_HostAddress/api/Utilisateur/1
Content-Type: application/json

{
    "Id": "1", 
    "Email": "NN.NP@example.com",
    "Password": "newpassword123",
    "PhoneNumber": "0987654321" 
}

###
### Supprimer un utilisateur
###

DELETE @Astate_HostAddress/api/Utilisateur/1